In [15]:
import numpy as np
import pandas as pd
import sklearn

np.set_printoptions(precision=6, suppress=True, edgeitems=10, linewidth=100000, 
                    formatter=dict(float=lambda x: f'{x:.2f}'))
np.random.seed(42)

### 1. Przygotowanie danych - uproszczone

In [16]:
from sklearn.datasets import load_breast_cancer

In [17]:
raw_data = load_breast_cancer()
print(raw_data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [18]:
all_data = raw_data.copy()

In [19]:
data = all_data['data']
target = all_data['target']

In [23]:
target[:3]

array([0, 0, 0])

### 3. Standaryzaja bez podzału na train /test :

scaler = StandardScaler()

scaler.fit(X_train)




X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)


a) w przypadku zbiorów train/test:

    - fit stosujemy tylko do X_train
    - transform dla X_train i X_test

#### - standaryzacja

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
X_train = data.copy()

scaler = StandardScaler()

scaler.fit(X_train)
X_train = scaler.transform(X_train)

#### - współczynniki

In [29]:
#średnia

scaler.mean_

array([14.13, 19.29, 91.97, 654.89, 0.10, 0.10, 0.09, 0.05, 0.18, 0.06, 0.41, 1.22, 2.87, 40.34, 0.01, 0.03, 0.03, 0.01, 0.02, 0.00, 16.27, 25.68, 107.26, 880.58, 0.13, 0.25, 0.27, 0.11, 0.29, 0.08])

In [30]:
# odchylenie standardowe
scaler.scale_

array([3.52, 4.30, 24.28, 351.60, 0.01, 0.05, 0.08, 0.04, 0.03, 0.01, 0.28, 0.55, 2.02, 45.45, 0.00, 0.02, 0.03, 0.01, 0.01, 0.00, 4.83, 6.14, 33.57, 568.86, 0.02, 0.16, 0.21, 0.07, 0.06, 0.02])

### 4. Inwersja - powrót do wcześniejszych wartości

#### - automatycznie

In [56]:
data[:5]

array([[17.99, 10.38, 122.80, 1001.00, 0.12, 0.28, 0.30, 0.15, 0.24, 0.08, 1.09, 0.91, 8.59, 153.40, 0.01, 0.05, 0.05, 0.02, 0.03, 0.01, 25.38, 17.33, 184.60, 2019.00, 0.16, 0.67, 0.71, 0.27, 0.46, 0.12],
       [20.57, 17.77, 132.90, 1326.00, 0.08, 0.08, 0.09, 0.07, 0.18, 0.06, 0.54, 0.73, 3.40, 74.08, 0.01, 0.01, 0.02, 0.01, 0.01, 0.00, 24.99, 23.41, 158.80, 1956.00, 0.12, 0.19, 0.24, 0.19, 0.28, 0.09],
       [19.69, 21.25, 130.00, 1203.00, 0.11, 0.16, 0.20, 0.13, 0.21, 0.06, 0.75, 0.79, 4.58, 94.03, 0.01, 0.04, 0.04, 0.02, 0.02, 0.00, 23.57, 25.53, 152.50, 1709.00, 0.14, 0.42, 0.45, 0.24, 0.36, 0.09],
       [11.42, 20.38, 77.58, 386.10, 0.14, 0.28, 0.24, 0.11, 0.26, 0.10, 0.50, 1.16, 3.44, 27.23, 0.01, 0.07, 0.06, 0.02, 0.06, 0.01, 14.91, 26.50, 98.87, 567.70, 0.21, 0.87, 0.69, 0.26, 0.66, 0.17],
       [20.29, 14.34, 135.10, 1297.00, 0.10, 0.13, 0.20, 0.10, 0.18, 0.06, 0.76, 0.78, 5.44, 94.44, 0.01, 0.02, 0.06, 0.02, 0.02, 0.01, 22.54, 16.67, 152.20, 1575.00, 0.14, 0.20, 0.40, 0.

In [57]:
X_train[:5]

array([[1.10, -2.07, 1.27, 0.98, 1.57, 3.28, 2.65, 2.53, 2.22, 2.26, 2.49, -0.57, 2.83, 2.49, -0.21, 1.32, 0.72, 0.66, 1.15, 0.91, 1.89, -1.36, 2.30, 2.00, 1.31, 2.62, 2.11, 2.30, 2.75, 1.94],
       [1.83, -0.35, 1.69, 1.91, -0.83, -0.49, -0.02, 0.55, 0.00, -0.87, 0.50, -0.88, 0.26, 0.74, -0.61, -0.69, -0.44, 0.26, -0.81, -0.10, 1.81, -0.37, 1.54, 1.89, -0.38, -0.43, -0.15, 1.09, -0.24, 0.28],
       [1.58, 0.46, 1.57, 1.56, 0.94, 1.05, 1.36, 2.04, 0.94, -0.40, 1.23, -0.78, 0.85, 1.18, -0.30, 0.81, 0.21, 1.42, 0.24, 0.29, 1.51, -0.02, 1.35, 1.46, 0.53, 1.08, 0.85, 1.96, 1.15, 0.20],
       [-0.77, 0.25, -0.59, -0.76, 3.28, 3.40, 1.92, 1.45, 2.87, 4.91, 0.33, -0.11, 0.29, -0.29, 0.69, 2.74, 0.82, 1.12, 4.73, 2.05, -0.28, 0.13, -0.25, -0.55, 3.39, 3.89, 1.99, 2.18, 6.05, 4.94],
       [1.75, -1.15, 1.78, 1.83, 0.28, 0.54, 1.37, 1.43, -0.01, -0.56, 1.27, -0.79, 1.27, 1.19, 1.48, -0.05, 0.83, 1.14, -0.36, 0.50, 1.30, -1.47, 1.34, 1.22, 0.22, -0.31, 0.61, 0.73, -0.87, -0.40]])

In [35]:
scaler.inverse_transform(X_train)[:2]

array([[17.99, 10.38, 122.80, 1001.00, 0.12, 0.28, 0.30, 0.15, 0.24, 0.08, 1.09, 0.91, 8.59, 153.40, 0.01, 0.05, 0.05, 0.02, 0.03, 0.01, 25.38, 17.33, 184.60, 2019.00, 0.16, 0.67, 0.71, 0.27, 0.46, 0.12],
       [20.57, 17.77, 132.90, 1326.00, 0.08, 0.08, 0.09, 0.07, 0.18, 0.06, 0.54, 0.73, 3.40, 74.08, 0.01, 0.01, 0.02, 0.01, 0.01, 0.00, 24.99, 23.41, 158.80, 1956.00, 0.12, 0.19, 0.24, 0.19, 0.28, 0.09]])

#### - inwersja ręczna:

- wzór  s = (x- x.mean) / x.std


- wzór odwrócony (inwersja)

s = (x- x.mean) / x.std    | * x.std

s * x.std = x- x.mean

x = s * x.std + x.mean

In [42]:
first_col = data[:,0]

In [45]:
mean = first_col.mean()
std = first_col.std()

#### - obliczenie s - standaryzacja

In [50]:
first_col_stand = (first_col - mean) / std

In [62]:
first_col_stand[:5] == X_train[:5,0]

array([False, False, False, False, False])

In [59]:
first_col_stand[:5]

array([1.10, 1.83, 1.58, -0.77, 1.75])

In [60]:
X_train[:5,0]

array([1.10, 1.83, 1.58, -0.77, 1.75])

In [66]:
np.allclose(first_col_stand[:5], X_train[:5,0])

True

#### - inwersja

In [69]:
first_col_inverse = first_col_stand * std + mean

In [70]:
first_col_inverse[:5]

array([17.99, 20.57, 19.69, 11.42, 20.29])

In [72]:
data[:5,0]

array([17.99, 20.57, 19.69, 11.42, 20.29])

In [73]:
first_col_inverse[:5] == data[:5,0]

array([ True,  True,  True,  True,  True])

In [74]:
np.array_equal(data[:5,0], first_col_inverse[:5])

True