In [1]:
import numpy as np
import pandas as pd
import sklearn

np.random.seed(42)
np.set_printoptions(precision=6, suppress=True)
sklearn.__version__

'1.0.1'

#### 1. Dane

In [2]:
pogoda = ['słonecznie', 'deszczowo', 'pochmurno', 'deszczowo', 'słonecznie', 'słonecznie',
          'pochmurno', 'pochmurno', 'słonecznie']
temperatura = ['ciepło', 'zimno', 'ciepło', 'ciepło', 'ciepło', 'umiarkowanie',
               'umiarkowanie', 'ciepło', 'zimno']

spacer = ['tak', 'nie', 'tak', 'nie', 'tak', 'tak', 'nie', 'tak', 'nie']      

raw_df = pd.DataFrame(data={'pogoda': pogoda, 'temperatura': temperatura, 'spacer': spacer})
df = raw_df.copy()
df

pogoda   temperatura spacer
0  słonecznie        ciepło    tak
1   deszczowo         zimno    nie
2   pochmurno        ciepło    tak
3   deszczowo        ciepło    nie
4  słonecznie        ciepło    tak
5  słonecznie  umiarkowanie    tak
6   pochmurno  umiarkowanie    nie
7   pochmurno        ciepło    tak
8  słonecznie         zimno    nie

#### 2.Przygotowanie danych do modelu

#### - target

In [3]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()
df['spacer'] = le.fit_transform(df['spacer'])
df

pogoda   temperatura  spacer
0  słonecznie        ciepło       1
1   deszczowo         zimno       0
2   pochmurno        ciepło       1
3   deszczowo        ciepło       0
4  słonecznie        ciepło       1
5  słonecznie  umiarkowanie       1
6   pochmurno  umiarkowanie       0
7   pochmurno        ciepło       1
8  słonecznie         zimno       0

#### - variables

In [9]:
df_dummy = pd.get_dummies(df, columns=['pogoda', 'temperatura'], drop_first=True)

In [10]:
df_dummy

spacer  pogoda_pochmurno  pogoda_słonecznie  temperatura_umiarkowanie  \
0       1                 0                  1                         0   
1       0                 0                  0                         0   
2       1                 1                  0                         0   
3       0                 0                  0                         0   
4       1                 0                  1                         0   
5       1                 0                  1                         1   
6       0                 1                  0                         1   
7       1                 1                  0                         0   
8       0                 0                  1                         0   

   temperatura_zimno  
0                  0  
1                  1  
2                  0  
3                  0  
4                  0  
5                  0  
6                  0  
7                  0  
8                  1

#### data, target

In [11]:
data = df_dummy.copy()
target = data.pop('spacer')

#### 3. Bayes Gaussian model

In [19]:
from sklearn.naive_bayes import GaussianNB

In [20]:
model = GaussianNB()
model.fit(data, target)
model.score(data, target)

0.7777777777777778

#### 4. Predykcja na podstawie pierwszego wiersza

In [35]:
first_row = data.iloc[0].to_frame().T

In [36]:
first_row

pogoda_pochmurno  pogoda_słonecznie  temperatura_umiarkowanie  \
0                 0                  1                         0   

   temperatura_zimno  
0                  0

In [37]:
first = first_row.values

In [39]:
prediction = model.predict(first_row)

In [40]:
prediction

array([1], dtype=int64)

In [46]:
le.classes_[prediction[0]]

1

In [52]:
le.classes_

array([0, 1])

In [56]:
model.predict_proba(first_row)

array([[0.000006, 0.999994]])