In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
#Dane:

data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']}

df_raw = pd.DataFrame(data)

# kopia zapasowa
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

### 1. Standaryzacja ręczna:

(x - Xmu) / Xstd

#### - pandas - estymator nieobciążony

In [3]:
(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [34]:
df['price'].var()

2350.0

In [35]:
df['price'].std()

48.47679857416329

#### - numpy - estymator obciążony

In [36]:
price = df['price'].to_numpy()
price

array([199.,  89.,  99., 129.,  79.])

In [37]:
price.var()

1880.0

In [38]:
price.std()

43.3589667773576

In [9]:
(price - price.mean())/ price.std()

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

#### - funkcja:

In [10]:
def standarize(x):
    return (x- x.mean()) / x.std()

In [11]:
# pandas

standarize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

#### - odwrócenie wzoru

In [12]:
df['price']

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

In [13]:
# odwrócenie wzoru:

s = standarize(df['price'])

# s= (x -x.mean) / x.std
price_mean = 119
price_std = 43.358966777357
s = standarize(price)


In [14]:
# wyprowadzenie wzoru
"""
s= (x -x.mean) / x.std                      wzór

s= (x -x.mean) / x.std  // * std            mnożymy przez prawy mianownik

s * std = x - x.mean                        

x - x.mean = s * std                        zamiana strom

x = s * std + x.mean                        wzór na x
"""

price = s * price_std + price_mean
price

array([199.,  89.,  99., 129.,  79.])

### 2. Zadanie z Data Science Bootcamp

Ustaw ziarno losowe na wartość 30. Następnie zbuduj dwuwymiarową tablicę o kształcie (10, 4) wartości pseudolosowo wygenerowanych z rozkładu normalego  N(100,5).

μ=100 

σ2=5

In [15]:
np.random.seed(30)
mu = 100
sigma = np.sqrt(5)

In [16]:
np.random.randn(10,4) 

array([[-1.26405266,  1.52790535, -0.97071094,  0.47055962],
       [-0.10069672,  0.30379318, -1.72596243,  1.58509537],
       [ 0.13429659, -1.10685547,  1.57822555,  0.10749794],
       [-0.76404783, -0.77518851,  1.38384717,  0.76038508],
       [-0.28564551,  0.53836748, -2.08389663,  0.93778171],
       [-0.005778  , -0.46747897, -0.4230153 ,  1.06448209],
       [-2.9033676 ,  1.61689037,  1.42550989, -0.66475512],
       [ 0.98501786, -1.70046527, -1.10014381, -1.31564409],
       [ 0.81050091, -1.04477837, -0.68922937, -0.85275686],
       [ 1.11347211, -1.92116972, -0.70140242,  0.84908785]])

In [17]:
np.random.randn(10,4) * sigma + mu

array([[102.34943615,  98.79951222,  99.9347231 , 103.11720395],
       [ 99.11034135, 102.27883811, 104.24602767,  99.20653207],
       [ 99.13460486,  95.69041414, 101.23152918, 102.13400447],
       [101.75034147,  95.99019815, 102.77687331, 103.8186381 ],
       [100.72259296,  97.78219087,  97.39882154,  99.95229327],
       [ 96.46255099,  97.22031218,  99.08283418,  97.64077982],
       [ 97.63577818,  97.12862661, 102.0418119 ,  96.89690708],
       [100.06714412,  98.99375205, 100.45980967,  98.97135019],
       [ 99.61223676,  99.51554504,  99.41876804, 101.26627061],
       [102.21487558,  98.67006883, 100.76800657,  94.21009881]])

### 3. Wnioskowanie statystyczne

https://www.fuw.edu.pl/~prozanski/WS/?var




### Estymator dla znanej wartości oczekiwanej

Ten estymator jest nieobciążony i zgodny, ale użyteczny tylko wówczas, gdy znamy prawdziwą wartość oczekiwaną μ populacji. W przeciwnym wypadku, mamy do dyspozycji dwa estymatory i warto uważać aby ich nie pomylić.


In [18]:
X = np.array([199.0, 89.0, 99.0, 129.0, 79.0])
mu = np.mean(X)  # znana wartość oczekiwana


# wariancja
s2 = np.sum( (X - mu)**2 ) / len(X)

# odchylenie standardowe jako pierwiastek z wariancji
s = np.sqrt(s2)

In [19]:
s2 

1880.0

In [20]:
s

43.3589667773576

In [21]:
np.var(X)

1880.0

In [22]:
np.std(X)

43.3589667773576

### Estymator nieobciążony wariancji

Z tego estymatora korzystamy wtedy, gdy nie znamy wariancji. Warto pamiętać, że o ile s21 jest estymatorem nieobciążonym wariancji, to s1 jako estymator odchylenia standardowego jest już obciążony.


In [23]:
X = np.array([199.0, 89.0, 99.0, 129.0, 79.0])

# wariancja
s2 = np.var(X, ddof=1)
# odchylenie standardowe czyli pierwiastek z wariancji
s = np.std(X, ddof=1)

#### - numpy - nieobciążony

In [24]:
s2

2350.0

In [25]:
s

48.47679857416329

#### - pandas - nieobciążony

In [26]:
price = df['price']

In [27]:
price.std()

48.47679857416329

In [28]:
price.var()

2350.0

#### - numpy obciążony

In [29]:
np.var(X)

1880.0

In [30]:
np.std(X)

43.3589667773576

### Estymator obciążony wariancji


Z tego estymatora raczej nie korzystamy, ale warto go odróżniać, ponieważ niekiedy wzory zapisane są z jego pomocą. Jest to też estymator największej wiarygodności.

In [31]:
import numpy
X = np.array([199.0, 89.0, 99.0, 129.0, 79.0])

# wariancja
s2 = numpy.var(X)

# odchylenie standardowe czyli pierwiastek z wariancji
s = numpy.std(X)

In [32]:
s2

1880.0

In [33]:
s

43.3589667773576