In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
#Dane:

data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']}

df_raw = pd.DataFrame(data)

# kopia zapasowa
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

### 1. Standaryzacja ręczna:

(x - Xmu) / Xstd

#### - pandas - estymator nieobciążony

In [8]:
(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [9]:
df['price'].var()

2350.0

In [10]:
df['price'].std()

48.47679857416329

#### - numpy - estymator obciążony

In [11]:
price = df['price'].to_numpy()
price

array([199.,  89.,  99., 129.,  79.])

In [12]:
price.var()

1880.0

In [13]:
price.std()

43.3589667773576

In [14]:
(price - price.mean())/ price.std()

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

#### - funkcja:

In [15]:
def standarize(x):
    return (x- x.mean()) / x.std()

In [16]:
# pandas

standarize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

#### - odwrócenie wzoru

In [17]:
df['price']

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

In [18]:
# odwrócenie wzoru:

s = standarize(df['price'])

# s= (x -x.mean) / x.std
price_mean = 119
price_std = 43.358966777357
s = standarize(price)


In [48]:
# wyprowadzenie wzoru
"""
s= (x -x.mean) / x.std                      wzór

s= (x -x.mean) / x.std  // * std            mnożymy przez prawy mianownik

s * std = x - x.mean                        

x - x.mean = s * std                        zamiana strom

x = s * std + x.mean                        wzór na x
"""

price = s * price_std + price_mean
price

array([199.,  89.,  99., 129.,  79.])

### 2. Zadanie z Data Science Bootcamp

Ustaw ziarno losowe na wartość 30. Następnie zbuduj dwuwymiarową tablicę o kształcie (10, 4) wartości pseudolosowo wygenerowanych z rozkładu normalego  N(100,5).

μ=100 

σ2=5

In [19]:
np.random.seed(30)
mu = 100
sigma = np.sqrt(5)

In [49]:
np.random.randn(10,4) 

array([[ 1.05069979, -0.53687446, -0.02919272,  1.39405598],
       [-0.39786744,  1.01912738,  1.8988813 , -0.35484964],
       [-0.38701647, -1.92730539,  0.55075659,  0.95435581],
       [ 0.7827765 , -1.7932379 ,  1.2418555 ,  1.70774688],
       [ 0.3231534 , -0.99183439, -1.16328237, -0.0213351 ],
       [-1.58199529, -1.24311418, -0.41016902, -1.05507534],
       [-1.05731214, -1.28411722,  0.91312604, -1.38774534],
       [ 0.03002776, -0.45000776,  0.20563314, -0.46002618],
       [-0.17341299, -0.21665484, -0.25993484,  0.56629343],
       [ 0.99052247, -0.5947633 ,  0.34346298, -2.58932253]])

In [20]:
np.random.randn(10,4) * sigma + mu

array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])

### 3. Wnioskowanie statystyczne

https://www.fuw.edu.pl/~prozanski/WS/?var




### Estymator dla znanej wartości oczekiwanej

Ten estymator jest nieobciążony i zgodny, ale użyteczny tylko wówczas, gdy znamy prawdziwą wartość oczekiwaną μ populacji. W przeciwnym wypadku, mamy do dyspozycji dwa estymatory i warto uważać aby ich nie pomylić.


In [21]:
X = np.array([199.0, 89.0, 99.0, 129.0, 79.0])
mu = np.mean(X)  # znana wartość oczekiwana


# wariancja
s2 = np.sum( (X - mu)**2 ) / len(X)

# odchylenie standardowe jako pierwiastek z wariancji
s = np.sqrt(s2)

In [22]:
s2 

1880.0

In [23]:
s

43.3589667773576

In [24]:
np.var(X)

1880.0

In [25]:
np.std(X)

43.3589667773576

### Estymator nieobciążony wariancji

Z tego estymatora korzystamy wtedy, gdy nie znamy wariancji. Warto pamiętać, że o ile s21 jest estymatorem nieobciążonym wariancji, to s1 jako estymator odchylenia standardowego jest już obciążony.


In [37]:
X = np.array([199.0, 89.0, 99.0, 129.0, 79.0])

# wariancja
s2 = np.var(X, ddof=1)
# odchylenie standardowe czyli pierwiastek z wariancji
s = np.std(X, ddof=1)

#### - numpy - nieobciążony

In [38]:
s2

2350.0

In [39]:
s

48.47679857416329

#### - pandas - nieobciążony

In [43]:
price = df['price']

In [44]:
price.std()

48.47679857416329

In [45]:
price.var()

2350.0

#### - numpy obciążony

In [47]:
np.var(X)

1880.0

In [48]:
np.std(X)

43.3589667773576

### Estymator obciążony wariancji


Z tego estymatora raczej nie korzystamy, ale warto go odróżniać, ponieważ niekiedy wzory zapisane są z jego pomocą. Jest to też estymator największej wiarygodności.

In [58]:
import numpy
X = np.array([199.0, 89.0, 99.0, 129.0, 79.0])

# wariancja
s2 = numpy.var(X)

# odchylenie standardowe czyli pierwiastek z wariancji
s = numpy.std(X)

In [59]:
s2

1880.0

In [60]:
s

43.3589667773576